name: build-test-deploy
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v5
      - name: use node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v5
      - name: use node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm test

  deploy:
    needs: test

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: use node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
      - name: configure github pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next
      - run: npm install
      - run: npm run build
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: './out'
      - name: deploy